### ISSUE TITLE
2.6.2 Release Notes Extension for VSTS - Cannot bind argument to parameter 'Message' because it is null.

### ISSUE THREAD

**Issue by johnnavarra** [rfennell/vNextBuild#101]
### VSTS Extension you are using
Release Notes Extension

### Where are you running it?
VSTS

### Version of Extension/Task
2.6.2

### Expected behavior and actual behavior
Expected: Extension task runs without error
Actual: Error message 

### Steps to reproduce the problem
Build setup: Build Agent installed on local build machine to run Continuous Integration tests.
After MSBuild completes I have the Generate Release Notes task start with
OutputFile: $(BUILD.STAGINGDIRECTORY)/releasenotes.md
Inline Template Location with this template:
_#Release notes for build $defname  
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  
###Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
###Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
@@CSLOOP@@_   

I have default credentials checked.

I receive the following message when it runs:
2017-03-23T18:58:32.4298505Z ##[section]Starting: Generate release notes
2017-03-23T18:58:32.4428594Z Preparing task execution handler.
2017-03-23T18:58:32.7748425Z Executing the powershell script: C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.6.2\GenerateReleaseNotes.ps1
2017-03-23T18:58:32.7748425Z **Build Number**  : $($build.buildnumber)    
2017-03-23T18:58:32.7748425Z **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
2017-03-23T18:58:32.7748425Z **Source Branch** : $($build.sourceBranch)  
2017-03-23T18:58:32.7748425Z ###Associated work items  
2017-03-23T18:58:32.7748425Z @@WILOOP@@  
2017-03-23T18:58:32.7748425Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
2017-03-23T18:58:32.7748425Z @@WILOOP@@  
2017-03-23T18:58:32.7748425Z ###Associated change sets/commits  
2017-03-23T18:58:32.7748425Z @@CSLOOP@@  
2017-03-23T18:58:32.7748425Z * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
2017-03-23T18:58:32.7748425Z @@CSLOOP@@)
2017-03-23T18:58:33.8308569Z ##[error]System.ArgumentException: Invalid JSON primitive: .
2017-03-23T18:58:33.8308569Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2017-03-23T18:58:33.8308569Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2017-03-23T18:58:33.8308569Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2017-03-23T18:58:33.8308569Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2017-03-23T18:58:33.8308569Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2017-03-23T18:58:33.8308569Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
2017-03-23T18:58:33.8308569Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2017-03-23T18:58:33.8908587Z ##[warning]Unable to get associated work items, most likely cause is the build has been deleted
2017-03-23T18:58:33.8928680Z ##[warning]Invalid JSON primitive: .
2017-03-23T18:58:33.9478600Z ##[warning]Unable to get details of changeset/commit, most likely cause is the build has been deleted
2017-03-23T18:58:33.9478600Z ##[warning]Invalid JSON primitive: .
2017-03-23T18:58:34.0278835Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
2017-03-23T18:58:34.0278835Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-03-23T18:58:34.0288638Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-03-23T18:58:34.0288638Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-03-23T18:58:34.0288638Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-03-23T18:58:34.0288638Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-03-23T18:58:34.0288638Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-03-23T18:58:34.0778677Z ##[error]PowerShell script completed with 2 errors.
2017-03-23T18:58:34.0788654Z ##[section]Finishing: Generate release notes

**Comment by rfennell** [comment]
- You are not getting back valid JSON from the API - Why?
- It thinks the build is delete 'Unable to get associated work items, most likely cause is the build has been deleted' - again why?

OK a few things to look at

1. On the build variable set the system.debug variable to true - this gives a more detailed error log
2. Try with the use default credentials parameter on the task set to false

**Comment by johnnavarra** [comment]
Hi Richard,
I messed around with the settings and got it working.
This works with
Default Credentials Off
Primary Artifact Off
Release Only Off

do you still want the logs for it?

**Comment by rfennell** [comment]
No if you are working that is great

**Comment by AppleEducate** [comment]
Im getting this error: 
cannot process [**Release completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$release.modifiedOn) ]

After running debug mode on the same bug I am having about message being 'null'

**Comment by rfennell** [comment]
@AppleEducate are you using the task in a build or a release? 

Reason I ask the $release variable is only set in a release. If in a build use a build specific sample from the [templates in this repo](https://github.com/rfennell/vNextBuild/tree/master/SampleTemplates/GenerateReleaseNotes%20(Original%20Powershell%20based)).

If the problems persist please log it as a new issue with a detailed debug log (set the build variable system.debug = true), it can get confusing when a new issue is logged against an old one.

**Comment by AppleEducate** [comment]
I am using this in a release. I have tried using in a build too and am getting the same error. I am using the default template. I will contine to troubleshoot and submit a new issue if I cannot resolve. Thank you

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube
