### ISSUE TITLE
GenerateReleaseNotes causing Cannot bind argument to parameter 'Message' because it is null error

### ISSUE THREAD

**Issue by patnolan** [rfennell/vNextBuild#228]
Hi,

The "Generate release notes" step included in my TFS Release Definition has been working fine. However, I just increased my linked artefact sources from one TFS build to three TFS builds. 

Now I get the following error. Do you know what I might be doing wrong?

_Note if I select "Generate for only primary artifact" it work but then I don't get changeset details for all 3 builds._

2017-12-21T03:07:43.8862921Z ##[section]Starting: Generate release notes
2017-12-21T03:07:43.8862921Z ==============================================================================
2017-12-21T03:07:43.8862921Z Task         : Generate Release Notes
2017-12-21T03:07:43.8862921Z Description  : Generates a release notes file in a format of your choice
2017-12-21T03:07:43.8862921Z Version      : 2.10.2
2017-12-21T03:07:43.8862921Z Author       : Black Marble
2017-12-21T03:07:43.8862921Z Help         : Version: 2.10.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2017-12-21T03:07:43.8862921Z ==============================================================================
2017-12-21T03:07:43.9175785Z Preparing task execution handler.
2017-12-21T03:07:44.3081900Z Executing the powershell script: C:\tfsbuild\agent3\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.10.2\GenerateReleaseNotes.ps1
2017-12-21T03:07:44.3081900Z **Build Number**  : $($build.buildnumber)    
2017-12-21T03:07:44.3081900Z **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
2017-12-21T03:07:44.3081900Z **Source Branch** : $($build.sourceBranch)  
2017-12-21T03:07:44.3081900Z ###Associated work items  
2017-12-21T03:07:44.3081900Z @@WILOOP@@  
2017-12-21T03:07:44.3081900Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
2017-12-21T03:07:44.3081900Z @@WILOOP@@  
2017-12-21T03:07:44.3081900Z ###Associated change sets/commits  
2017-12-21T03:07:44.3081900Z @@CSLOOP@@  
2017-12-21T03:07:44.3081900Z * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
2017-12-21T03:07:44.3081900Z @@CSLOOP@@)
2017-12-21T03:07:46.6823419Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-21T03:07:46.6823419Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-21T03:07:46.9480063Z ##[error]PowerShell script completed with 1 errors.
2017-12-21T03:07:46.9636305Z ##[section]Finishing: Generate release notes

**The Inline template is**

#Release notes for build $defname  
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  
###Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
###Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
@@CSLOOP@@

**Comment by rfennell** [comment]
I think you are missing an outer @@buildloop@@ tag, so when it has more than one build it cannot iterate across them. 

[For a sample see here](https://raw.githubusercontent.com/rfennell/vNextBuild/master/SampleTemplates/GenerateReleaseNotes%20(Original%20Powershell%20based)/release-basic-template.md)

Let me know if that fixes it
