### ISSUE TITLE
Method invocation failed because [System.Char] does not contain a method named 'Trim'.

### ISSUE THREAD

**Issue by BartVDACodeware** [rfennell/vNextBuild#30]
Hi, I installed the 'Generate Release Notes Build Task' plugin in VSTS.
When I add a build step, on build time the following error occurred:

_System.Management.Automation.RuntimeException: Method invocation failed because [System.Char] does not contain a method named 'Trim'.
at CallSite.Target(Closure , CallSite , Object )
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)_

I followed this document: https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks

**Comment by rfennell** [comment]
Have a look at this [thread](https://github.com/rfennell/vNextBuild/issues/14), as I think this is potentially the same one.

If so it an issue with the template, try one of the samples.

**Comment by rfennell** [comment]
Has this fixed your issue? If I hear nothing back in a week I will close the issue
