### ISSUE TITLE
BuildTasks Task appears to be broken

### ISSUE THREAD

**Issue by macksta** [rfennell/vNextBuild#308]
### VSTS Extension you are using
https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task

### Where are you running it?
VSTS

### Version of Extension/Task
Latest

### Expected behaviour and actual behaviour
**Expected behaviour**
Variable will be updated with new value

**Actual Behaviour**
Task fails,

### Steps to reproduce the problem
Add task to build

Enter the following data:
Variable to update: BuildConfiguration
Update Mode: manual
Value to set: debug

**LOG FILE**

2018-04-13T06:40:29.6908081Z ##[section]Starting: Update BuildConfiguration to debug for demo branch's
2018-04-13T06:40:29.7097413Z ==============================================================================
2018-04-13T06:40:29.7097582Z Task         : Set variable on a build defintion
2018-04-13T06:40:29.7097703Z Description  : Set variable on a build defintion
2018-04-13T06:40:29.7097837Z Version      : 1.7.5
2018-04-13T06:40:29.7097944Z Author       : Richard Fennell
2018-04-13T06:40:29.7098077Z Help         : Version: 1.7.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task/)
2018-04-13T06:40:29.7098239Z ==============================================================================
2018-04-13T06:40:29.7357873Z Preparing task execution handler.
2018-04-13T06:40:42.7185095Z Executing the powershell script: D:\a\_tasks\BuildVariableTask_115030de-9ced-4d2f-ad01-8c42d20d0327\1.7.5\BuildVariableTask.ps1
2018-04-13T06:40:45.5206486Z ##[error]System.ArgumentException: Invalid JSON primitive: .
2018-04-13T06:40:45.5221240Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2018-04-13T06:40:45.5221461Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-13T06:40:45.5221653Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2018-04-13T06:40:45.5221889Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2018-04-13T06:40:45.5222095Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2018-04-13T06:40:45.5222281Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2018-04-13T06:40:45.5222436Z    at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-13T06:40:45.8072252Z ##[error]System.ArgumentException: Invalid JSON primitive: .
2018-04-13T06:40:45.8073096Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2018-04-13T06:40:45.8073509Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2018-04-13T06:40:45.8073800Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2018-04-13T06:40:45.8074102Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2018-04-13T06:40:45.8074387Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2018-04-13T06:40:45.8074634Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2018-04-13T06:40:45.8074890Z    at System.Management.Automation.CommandProcessorBase.Complete()
2018-04-13T06:40:45.9512898Z ##[error]System.Management.Automation.RuntimeException: The property 'value' cannot be found on this object. Verify that the property exists and can be set.
2018-04-13T06:40:45.9513513Z    at CallSite.Target(Closure , CallSite , Object , String )
2018-04-13T06:40:45.9514685Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2018-04-13T06:40:45.9515006Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-04-13T06:40:45.9515360Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-04-13T06:40:46.2104232Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "UploadString" with "3" argument(s): "Value cannot be null.
2018-04-13T06:40:46.2105013Z Parameter name: data" ---> System.ArgumentNullException: Value cannot be null.
2018-04-13T06:40:46.2107089Z Parameter name: data
2018-04-13T06:40:46.2107389Z    at System.Net.WebClient.UploadString(Uri address, String method, String data)
2018-04-13T06:40:46.2109504Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
2018-04-13T06:40:46.2109660Z    --- End of inner exception stack trace ---
2018-04-13T06:40:46.2109854Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2018-04-13T06:40:46.2110073Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
2018-04-13T06:40:46.2110246Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
2018-04-13T06:40:46.2110591Z    at System.Management.Automation.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
2018-04-13T06:40:46.2110789Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-04-13T06:40:46.2842261Z ##[error]PowerShell script completed with 4 errors.
2018-04-13T06:40:46.2854069Z ##[section]Finishing: Update BuildConfiguration to debug for demo branch's

**Comment by rfennell** [comment]
This could be a rights issue, the build service account usually does not have rights to update the build template (which is what is occuring with this task)

This is issue is documented, with the fix, at the foot of the page in the projects wiki https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
