### ISSUE TITLE
Error Generating Version Number

### ISSUE THREAD

**Issue by Akinnagbe** [rfennell/vNextBuild#359]
Hello Richard, am really sorry for disturbing, but it's not recognizing the variables, i got this error:

Could not find version number data in 63.$(DayOfMonth) that matches \d+\.\d+.

i still don't know what am missing.

Please assist. Thanks

Version Number Used:
$(StartRelease).$(Date:yyyyMMdd)
NOTE: $(StartRelease) as been defined as 63 in my variables

Error Message

2018-08-17T10:00:13.0762666Z ##[debug]Evaluating condition for step: 'Version Android Manifest'
2018-08-17T10:00:13.0763358Z ##[debug]Evaluating: succeeded()
2018-08-17T10:00:13.0763608Z ##[debug]Evaluating succeeded:
2018-08-17T10:00:13.0764066Z ##[debug]=> True
2018-08-17T10:00:13.0764408Z ##[debug]Result: True
2018-08-17T10:00:13.0764731Z ##[section]Starting: Version Android Manifest
2018-08-17T10:00:13.0770229Z ==============================================================================
2018-08-17T10:00:13.0770530Z Task         : Version Android Manifest
2018-08-17T10:00:13.0770838Z Description  : Applies a version to an Android Manifest via the versionCode property based on the build number.
2018-08-17T10:00:13.0771104Z Version      : 1.42.2
2018-08-17T10:00:13.0771330Z Author       : Black Marble
2018-08-17T10:00:13.0771656Z Help         : Version: 1.42.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Version-Assemblies-and-Packages-Tasks/)
2018-08-17T10:00:13.0771998Z ==============================================================================
2018-08-17T10:00:13.4796480Z ##[debug]agent.workFolder=D:\vstsagent\vsts-agent-win-x64-2.138.6\_work
2018-08-17T10:00:13.4884807Z ##[debug]loading inputs and endpoints
2018-08-17T10:00:13.4893316Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-08-17T10:00:13.4906932Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-08-17T10:00:13.4910184Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-08-17T10:00:13.4912761Z ##[debug]loading INPUT_FILENAMEPATTERN
2018-08-17T10:00:13.4914967Z ##[debug]loading INPUT_OUTPUTVERSION
2018-08-17T10:00:13.4917606Z ##[debug]loading INPUT_PATH
2018-08-17T10:00:13.4919715Z ##[debug]loading INPUT_VERSIONCODEFORMAT
2018-08-17T10:00:13.4922198Z ##[debug]loading INPUT_VERSIONNAMEFORMAT
2018-08-17T10:00:13.4924259Z ##[debug]loading INPUT_VERSIONNUMBER
2018-08-17T10:00:13.4926963Z ##[debug]loading INPUT_VERSIONREGEX
2018-08-17T10:00:13.4934140Z ##[debug]loading SECRET_KEYSTOREALIAS
2018-08-17T10:00:13.4937311Z ##[debug]loading SECRET_KEYSTOREPASS
2018-08-17T10:00:13.4945724Z ##[debug]loaded 12
2018-08-17T10:00:13.4962477Z ##[debug]Path=D:\vstsagent\vsts-agent-win-x64-2.138.6\_work\1\s
2018-08-17T10:00:13.4969522Z ##[debug]VersionNumber=63.$(Date:yyyyMMdd)
2018-08-17T10:00:13.4972621Z ##[debug]VersionRegex=\d+\.\d+
2018-08-17T10:00:13.4991815Z ##[debug]VersionNameFormat={1}.{2}
2018-08-17T10:00:13.4993069Z ##[debug]VersionCodeFormat={3}
2018-08-17T10:00:13.4994168Z ##[debug]outputversion=OutputedVersion
2018-08-17T10:00:13.4996714Z ##[debug]FilenamePattern=AndroidManifest.xml
2018-08-17T10:00:13.5012659Z Source Directory:  D:\vstsagent\vsts-agent-win-x64-2.138.6\_work\1\s
2018-08-17T10:00:13.5013069Z Filename Pattern: AndroidManifest.xml
2018-08-17T10:00:13.5013414Z Version Number/Build Number: 63.$(Date:yyyyMMdd)
2018-08-17T10:00:13.5013734Z Version Filter to extract build number: \d+\.\d+
2018-08-17T10:00:13.5014031Z Version Number Format: {1}.{2}
2018-08-17T10:00:13.5014310Z Version Code Format: {3}
2018-08-17T10:00:13.5014633Z Output: Version Number Parameter Name: OutputedVersion
2018-08-17T10:00:13.6403807Z Found 1 files to update.
2018-08-17T10:00:13.6508361Z ##[error]Could not find version number data in 63.$(Date:yyyyMMdd) that matches \d+\.\d+.
2018-08-17T10:00:13.6520570Z ##[debug]Processed: ##vso[task.issue type=error;]Could not find version number data in 63.$(Date:yyyyMMdd) that matches \d+\.\d+.
2018-08-17T10:00:13.6590523Z ##[error]Exit code 1 returned from process: file name 'D:\vstsagent\vsts-agent-win-x64-2.138.6\externals\node\bin\node.exe', arguments '"D:\vstsagent\vsts-agent-win-x64-2.138.6\_work\_tasks\VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d\1.42.2\ApplyVersionToManifest.js"'.
2018-08-17T10:00:13.6624807Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'D:\vstsagent\vsts-agent-win-x64-2.138.6\externals\node\bin\node.exe', arguments '"D:\vstsagent\vsts-agent-win-x64-2.138.6\_work\_tasks\VersionAndroidManifest_3fccabf1-a604-48c1-a96c-9f5f1841391d\1.42.2\ApplyVersionToManifest.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-08-17T10:00:13.6629358Z ##[section]Finishing: Version Android Manifest

**Comment by rfennell** [comment]
OK I think I see the problem, as you said in your marketplace query (sorry I missunderstood) you are setting the parameters of the task to

```
2018-08-17T10:00:13.4969522Z ##[debug]VersionNumber=63.$(Date:yyyyMMdd)
2018-08-17T10:00:13.4972621Z ##[debug]VersionRegex=\d+.\d+
```
The first line should be something like

`2018-08-17T10:00:13.4969522Z ##[debug]VersionNumber=63.20180817`

The version number is built in by the build process, so on the build, options page in the build number format, this should be set to **63.$(Date:yyyyMMdd)**. The build will then expand the $(...) parameter

**Comment by Akinnagbe** [comment]
Thanks for the reply, much appreciated.
i did as you explained, change the Version number to $(Build.BuildNumber) and it worked.

 I think the way I versioned the release wasn't okay, i did something like this 60.0,61.0 ... 63.0. I would like to restructure it to this 1.2.00001 so that I can take it directly from the build options. 
Can you suggest a way to do that. I mean reset the version Number 

Thumbs up

**Comment by Akinnagbe** [comment]
Thanks for the update, really helpful.

Regards

**Comment by rfennell** [comment]
Great, glad to be of help, I will close this issue down, but re-open it if you need to add more questions, or just add more comments
