### ISSUE TITLE
[GenerateReleaseNotes] RuntimeException: Cannot convert null to type "System.DateTime"

### ISSUE THREAD

**Issue by knom** [rfennell/vNextBuild#36]
I'm getting the following error..

```
2016-08-22T14:40:47.2216824Z ##[debug]Processing template
2016-08-22T14:40:47.2998067Z ##[error]System.Management.Automation.RuntimeException: Cannot convert null to type "System.DateTime". ---> System.Management.Automation.PSInvalidCastException: Cannot convert null to type "System.DateTime".
2016-08-22T14:40:47.2998067Z ##[error]   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
2016-08-22T14:40:47.2998067Z ##[error]   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
2016-08-22T14:40:47.2998067Z ##[error]   at CallSite.Target(Closure , CallSite , Object )
2016-08-22T14:40:47.2998067Z ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2016-08-22T14:40:47.2998067Z ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
2016-08-22T14:40:47.2998067Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-22T14:40:47.2998067Z ##[error]   --- End of inner exception stack trace ---
```

**Comment by knom** [comment]
I guess, this is because of your sample template, doing casts to DateTime..
https://github.com/rfennell/vNextBuild/blob/master/Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1

**Comment by rfennell** [comment]
Yes you need to be careful that the template you use only references objects and properties present in your build. DateTimes can be an issue as some are not set until the build/release is complete
