### ISSUE TITLE
Getting MethodInvocationException for MSTestAdapter.PlatformServices assembly

### ISSUE THREAD

**Issue by sysdvj** [rfennell/vNextBuild#365]
### VSTS Extension you are using
Task         : StyleCop Runner by Black Marble
Description  : Black Marble's StyleCop test runner that use settings files in the project 
Version      : 2.3.2
Author       : Black Marble

### Where are you running it?
*VSTS*

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

### Expected behaviour and actual behaviour
should be successful
settings : 
Sourcefilefolder - $(build.SourcesDirectory)/abc
max violation count  - 1000
allowed violation count - 0
enabled force analysis
enabled control option

### Steps to reproduce the problem
getting error.

##[error]System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Method 'get_Properties' in type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation." ---> System.TypeLoadException: Method 'get_Properties' in type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
2018-08-28T05:31:48.1515921Z    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
2018-08-28T05:31:48.1516823Z    at System.Reflection.RuntimeAssembly.GetExportedTypes()
2018-08-28T05:31:48.1517814Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1518607Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1519380Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1520178Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1520952Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1523577Z    at StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
2018-08-28T05:31:48.1524430Z    at StyleCop.StyleCopCore.Initialize(ICollection`1 addInPaths, Boolean loadFromDefaultPath)
2018-08-28T05:31:48.1525180Z    at StyleCopWrapper.Wrapper.Scan()
2018-08-28T05:31:48.1525822Z    at CallSite.Target(Closure , CallSite , Object )
2018-08-28T05:31:48.1526485Z    --- End of inner exception stack trace ---

**Comment by rfennell** [comment]
Looks like that MS Library is confusing StyleCop. As the error appears in StyleCop.StyleCopCore there is not much I can do, all I do is wrapper the stylecop DLLs they do all the loading.

My guess is the the DLL in question is being inspected and seen as a StyleCop ruleset, but it is not. 

No sure that the answer is, how does StyleCop in VS behave?

**Comment by sysdvj** [comment]
Thanks @rfennell . Same config and settings does works with another build definition and repo but for only one repo/build def it is causing issue. For now as a workaround i have updated Sourcefilefolder to $(build.SourcesDirectory) and it starts working. Not sure why.

In VS it is working fine.

**Comment by rfennell** [comment]
Strange, not sure what to offer as a suggestion other than stick with the workaround

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
