### ISSUE TITLE
When running a build that has no associated work items or commits the generate release notes task fails

### ISSUE THREAD

**Issue by baronmor** [rfennell/vNextBuild#5]
2016-03-24T16:35:38.0944568Z ##[error]System.Management.Automation.RuntimeException: Cannot index into a null array.

22 
2016-03-24T16:35:38.0944568Z ##[error]   at CallSite.Target(Closure , CallSite , Object , Int32 )

23 
2016-03-24T16:35:38.0944568Z ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)

24 
2016-03-24T16:35:38.0944568Z ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)

25 
2016-03-24T16:35:38.1100758Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

26 
2016-03-24T16:35:38.1100758Z ##[error]System.Management.Automation.RuntimeException: Cannot index into a null array.

27 
2016-03-24T16:35:38.1100758Z ##[error]   at CallSite.Target(Closure , CallSite , Object , Int32 )

28 
2016-03-24T16:35:38.1100758Z ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)

29 
2016-03-24T16:35:38.1100758Z ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)

30 
2016-03-24T16:35:38.1100758Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by rfennell** [comment]
Just checked on my test system that I get a set of release notes even if there are no associated work items or changesets. So ...
1. Can you provide me with the whole of the log for the generate release notes task, not just the error 
2. Also is what team process template (scum, agile etc) and source control (tfvc, git) are you using.
3. If you have either associated work items and changesets/commits does the task work as expected?

**Comment by baronmor** [comment]
[7_Generate release notes.txt](https://github.com/rfennell/vNextBuild/files/188693/7_Generate.release.notes.txt)

1. The log file is attached
2. The team process is agile and the source control is git
3. When building a branch that has changes (commits and work items) the task works as expected. 

Thanks :)

**Comment by rfennell** [comment]
I am surprised to see the enum declaration in the log, that's important, just not sure why!

Anyway I have put in more checks for empty template files, associated work items and commits.
It now writes a line into the output saying there are no associated items and to the log.

Not sure this will sort your issue, but the logging should give some more clues.
It has been uploaded to the marketplace and should auto install into your instance as verison 1.0.2

**Comment by baronmor** [comment]
[7_Generate release notes.txt](https://github.com/rfennell/vNextBuild/files/188933/7_Generate.release.notes.txt)

Thanks for looking into this and providing a quick fix. Unfortunately 1.0.2 does not solve the issue (see attached log). I suspect that the issue is with the template file, I copied your suggested template as is but perhaps I missed something. 
[template.zip](https://github.com/rfennell/vNextBuild/files/188934/template.zip)

**Comment by rfennell** [comment]
Yes it seems to be template related, if I use yours I see a null exception in the log, but still no enum debug line. I do get a set of release notes though

So I done test build with no workitems associated and 1 changeset where I run three templates: my simple standard template, a template that just does a drop of the objects (no layout field based formatting) and your template.

I have attached my templates, logs and output.

[logs.zip](https://github.com/rfennell/vNextBuild/files/189285/logs.zip)
[templates.zip](https://github.com/rfennell/vNextBuild/files/189280/templates.zip)
[output.zip](https://github.com/rfennell/vNextBuild/files/189293/output.zip)

Can you see if you get similar results. Sorry this is taking to long to resolve

**Comment by baronmor** [comment]
works ! :)

Much appreciated !

**Comment by rfennell** [comment]
I have update the documentation there new samples to try to make it clearer
