### ISSUE TITLE
Server 404 error if Git type artifact is linked to pipeline

### ISSUE THREAD

**Issue by gigeld** [rfennell/vNextBuild#56]
If a Git type artifact is linked to the release pipeline, the GenerateReleaseNotes task throws this error:
Error:
##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
at System.Net.WebClient.DownloadString(Uri address)
at CallSite.Target(Closure , CallSite , Object , Object )
--- End of inner exception stack trace ---
...

**Comment by rfennell** [comment]
I have only tested this task when the release is linked to an artifact that is a VSTS build, the task looks at the build details to generate the release notes.
There is no way to support a Git repo based artifact, but I think it should not error, it should skip this type of artifact. I will look into getting this done.

**Comment by gigeld** [comment]
Thank you! 
It will be nice as well if we can store the template in the Git repo so it can be reused in multiple pipelines ...

**Comment by rfennell** [comment]
You have the option to get the template from an build artifact, so what I do is have a build that just copies the contents of a repo, maybe templates or scripts, so they are available to be release pipeline. This gets around the issue of accessing these items and provides a means to version them

**Comment by rfennell** [comment]
Sorry I have a better answer on the storing templates in Git.

Just add the Git repo as an artifact in the release. Once this is done you can just browse to it using the File based template picker in as if the template was in the build as I previous discussed

**Comment by gigeld** [comment]
Thank you! It seems to work (the release notes file is generated), but regardless if I use inline template or from the Git repo the logs display this error:

**Comment by gigeld** [comment]
2016-12-01T12:47:47.6381368Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
 
2016-12-01T12:47:47.6381368Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
 
2016-12-01T12:47:47.6381368Z    at System.Net.WebClient.DownloadString(Uri address)
 
2016-12-01T12:47:47.6381368Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.6381368Z    --- End of inner exception stack trace ---
 
2016-12-01T12:47:47.6381368Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
 
2016-12-01T12:47:47.6381368Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.6381368Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 
2016-12-01T12:47:47.6381368Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2016-12-01T12:47:47.7181525Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
 
2016-12-01T12:47:47.7181525Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
 
2016-12-01T12:47:47.7191367Z    at System.Net.WebClient.DownloadString(Uri address)
 
2016-12-01T12:47:47.7191367Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.7191367Z    --- End of inner exception stack trace ---
 
2016-12-01T12:47:47.7191367Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
 
2016-12-01T12:47:47.7191367Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.7191367Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 
2016-12-01T12:47:47.7191367Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2016-12-01T12:47:47.7672026Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
 
2016-12-01T12:47:47.7672026Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
 
2016-12-01T12:47:47.7672026Z    at System.Net.WebClient.DownloadString(Uri address)
 
2016-12-01T12:47:47.7672026Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.7672026Z    --- End of inner exception stack trace ---
 
2016-12-01T12:47:47.7672026Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
 
2016-12-01T12:47:47.7672026Z    at CallSite.Target(Closure , CallSite , Object , Object )
 
2016-12-01T12:47:47.7672026Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 
2016-12-01T12:47:47.7672026Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2016-12-01T12:47:48.0192027Z ##[error]PowerShell script completed with 3 errors.

**Comment by rfennell** [comment]
I have tested this with a release that include multiple artifacts, some VSTS builds, other Git. It now only tries to get the wi and commits for the VSTS builds. Let me know if it works for you

Shipped in 1.5.1

**Comment by gigeld** [comment]
It's working. Thank you for your prompt support!
