### ISSUE TITLE
Generate Release Notes Task failing with unexplained error

### ISSUE THREAD

**Issue by jtphelpsAHIT** [rfennell/vNextBuild#79]
### VSTS Extension you are using
Generate Release Notes task

### Where are you running it?
VSTS

### Version of Extension/Task
Public / Latest

### Expected behavior and actual behavior
All of the sudden I am seeing the following message in the log output for the task. No changes have been made to the task config or the template since the last successful execution. I haven't defined a parameter named "Message" anywhere so I don't know what is causing the problem. 
Cannot bind argument to parameter 'Message' because it is null.

### Steps to reproduce the problem
Run the build definition with the task in it.

**Comment by rfennell** [comment]
This is down to the revised error handling. You have at have in your template that the task cannot render. Hence the message.

As long as you are happy with the release notes generated you can ignore the message. 

To fix it check your output against your template, check the first line not rendered and look at the variables you are using, one will be null (or one of it's properties).

**Comment by jtphelpsAHIT** [comment]
Thank you very much!

Jason

**Comment by ynijs** [comment]
Have been trying to get the extension to work as well, but I struggle with the exact same issue.
I've created an empty release definition and linking build artifacts to it, added one step, the release note generator, with the inline example that is listed here, specifically for releases. However, it's yielding the same result, a blank (placeholders replaced by void) template, with the error messages as above outputted in the log. Even the release number is not filled in.

**Comment by rfennell** [comment]
Can you set the build or release (which is it) to generate debug, set the variable system.debug to true

Then upload the log so I can see what is happening

**Comment by ynijs** [comment]
Sure, I had set it to debug=true already, here's the log (I sanitized a few things):

> 2017-02-22T21:46:07.8471442Z ##[section]Starting: Generate release notes
2017-02-22T21:46:07.8940210Z ==============================================================================
2017-02-22T21:46:07.8940210Z Task         : Generate Release Notes
2017-02-22T21:46:07.8940210Z Description  : Generates a Markdown Release notes file
2017-02-22T21:46:07.8940210Z Version      : 2.5.1
2017-02-22T21:46:07.8940210Z Author       : Black Marble
2017-02-22T21:46:07.8940210Z Help         : Version: 2.5.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2017-02-22T21:46:07.8940210Z ==============================================================================
2017-02-22T21:46:07.9408973Z Preparing task execution handler.
2017-02-22T21:46:10.1597177Z Executing the powershell script: C:\agent\xxxx\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.5.1\GenerateReleaseNotes.ps1
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddCommand(C:\agent\xxxx\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.5.1\GenerateReleaseNotes.ps1)
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddParameter(outputfile=C:\agent\xxxx\_work\r4\a\releasenotes.md)
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddParameter(outputVariableName=$(TestOutput))
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddParameter(templateLocation=InLine)
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddParameter(templatefile=C:\agent\xxxx\_work\r4\a)
2017-02-22T21:46:10.5034770Z ##[debug]PowerShellHandler.Execute - AddParameter(inlinetemplate=#Release notes for build $defname  
2017-02-22T21:46:10.5034770Z $($build)    
2017-02-22T21:46:10.5191044Z ###Associated work items  
2017-02-22T21:46:10.5191044Z @@WILOOP@@  
2017-02-22T21:46:10.5191044Z * $($widetail) 
2017-02-22T21:46:10.5191044Z @@WILOOP@@  
2017-02-22T21:46:10.5191044Z ###Associated change sets/commits  
2017-02-22T21:46:10.5191044Z @@CSLOOP@@  
2017-02-22T21:46:10.5191044Z * $($csdetail)    
2017-02-22T21:46:10.5191044Z @@CSLOOP@@)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - AddParameter(usedefaultcreds=true)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - AddParameter(emptySetText=None)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForOnlyPrimary=false)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForCurrentRelease=true)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - AddParameter(overrideStageName=)
2017-02-22T21:46:10.5191044Z ##[debug]PowerShellHandler.Execute - Invoke
2017-02-22T21:46:10.5191044Z ##[debug]Loading module from path 'C:\agent\xxxx\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.5.1\GenerateReleaseNotes.psm1'.
2017-02-22T21:46:10.5191044Z ##[debug]
2017-02-22T21:46:10.5191044Z    public enum Mode
2017-02-22T21:46:10.5191044Z    {
2017-02-22T21:46:10.5191044Z       BODY,
2017-02-22T21:46:10.5191044Z       WI,
2017-02-22T21:46:10.5191044Z       CS,
2017-02-22T21:46:10.5191044Z       BUILD
2017-02-22T21:46:10.5191044Z    }
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-BuildWorkItems'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-BuildChangeSets'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-Detail'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-Build'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-Release'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-BuildReleaseArtifacts'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Add-Space'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Invoke-GetCommand'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Render'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-Template'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-Mode'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Add-StackItem'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Invoke-Template'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-BuildDataSet'.
2017-02-22T21:46:10.5191044Z ##[debug]Exporting function 'Get-ReleaseByDefinitionId'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Add-Space'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Add-StackItem'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-Build'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-BuildChangeSets'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-BuildDataSet'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-BuildReleaseArtifacts'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-BuildWorkItems'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-Detail'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-Mode'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-Release'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-ReleaseByDefinitionId'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Get-Template'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Invoke-GetCommand'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Invoke-Template'.
2017-02-22T21:46:10.5191044Z ##[debug]Importing function 'Render'.
2017-02-22T21:46:10.5191044Z ##[debug]collectionUrl = [https://xxxx.visualstudio.com/]
2017-02-22T21:46:10.5191044Z ##[debug]teamproject = [xxx]
2017-02-22T21:46:10.5191044Z ##[debug]releaseid = [702]
2017-02-22T21:46:10.5191044Z ##[debug]releasedefid = [11]
2017-02-22T21:46:10.5191044Z ##[debug]stageName = [xxx]
2017-02-22T21:46:10.5191044Z ##[debug]overrideStageName = []
2017-02-22T21:46:10.5191044Z ##[debug]buildid = [1192]
2017-02-22T21:46:10.5191044Z ##[debug]defname = [EDF - AX - Nightly build]
2017-02-22T21:46:10.5191044Z ##[debug]buildnumber = [0.1.0.23]
2017-02-22T21:46:10.5347288Z ##[debug]outputVariableName = [$(TestOutput)]
2017-02-22T21:46:10.5347288Z ##[debug]In Release mode
2017-02-22T21:46:10.5347288Z ##[debug]Only processing current release
2017-02-22T21:46:10.5347288Z ##[debug]Getting details of release [702] from server [https://xxx.visualstudio.com//xxx]
2017-02-22T21:46:10.5347288Z ##[debug]Using default credentials
2017-02-22T21:46:10.5347288Z ##[error]System.ArgumentException: Invalid JSON primitive: .
2017-02-22T21:46:10.5347288Z ##[debug]Processed: ##vso[task.logissue type=error;]System.ArgumentException: Invalid JSON primitive: .
2017-02-22T21:46:10.5347288Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2017-02-22T21:46:10.5347288Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2017-02-22T21:46:10.5347288Z    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2017-02-22T21:46:10.5347288Z    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2017-02-22T21:46:10.5347288Z    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2017-02-22T21:46:10.5347288Z    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
2017-02-22T21:46:10.5347288Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2017-02-22T21:46:10.5347288Z ##[debug]Discovered [1] releases for processing
2017-02-22T21:46:10.5347288Z ##[debug]Processing the release []
2017-02-22T21:46:10.5347288Z ##[debug]Using template mode [InLine]
2017-02-22T21:46:10.5347288Z ##[debug]Using in-line template
2017-02-22T21:46:10.5347288Z ##[debug]Processing template
2017-02-22T21:46:10.5347288Z ##[debug]There are [1] builds to process
2017-02-22T21:46:10.5347288Z ##[debug]   Starting block WI
2017-02-22T21:46:10.5347288Z ##[debug]      1 items
2017-02-22T21:46:10.5347288Z ##[debug]      Getting first workitem 
2017-02-22T21:46:10.5347288Z ##[debug]   Ending block WI
2017-02-22T21:46:10.5347288Z ##[debug]   Starting block CS
2017-02-22T21:46:10.5347288Z ##[debug]      1 items
2017-02-22T21:46:10.5347288Z ##[debug]      Getting first changeset/commit 
2017-02-22T21:46:10.5347288Z ##[debug]   Ending block CS
2017-02-22T21:46:10.5347288Z ##[debug]Writing output file [C:\agent\xxxx\_work\r4\a\releasenotes.md].
2017-02-22T21:46:10.5347288Z ##[debug]Setting variable: [$(TestOutput)] = #Release notes for build         ###Associated work items   ###Associated change sets/commits   
2017-02-22T21:46:10.5347288Z ##[debug]Processed: ##vso[task.setvariable variable=$(TestOutput);]#Release notes for build         ###Associated work items   ###Associated change sets/commits   
2017-02-22T21:46:10.5347288Z 
2017-02-22T21:46:10.5347288Z 
2017-02-22T21:46:10.5503541Z ##[error]PowerShell script completed with 1 errors.
2017-02-22T21:46:10.5503541Z ##[section]Finishing: Generate release notes

>

**Comment by rfennell** [comment]
A couple of things 
- Looks like you are running the task inside a release (I can see the releaseID that has a value), but your inline release template has no @@Build tags, so it can only loop across the first build found within a release (try using this [sample](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/release-basic-template.md)) - _I don't think this is the issue by the way_
- You have the UseDefaultCredential parameter set to true - this is only needed for on premises installations (and frankly should not really be need) this needs to be false (the default) for VSTS - _I think this is the issue)

**Comment by ynijs** [comment]
Correct, was using it in a release definition. I must have taken the wrong example then...
By disabling the UseDefaultCredential parameter, the release note is generated, looks good!

Thanks!

**Comment by rfennell** [comment]
glad you are up and running
